d /run/salyut-bbs       0711 salyut-bbsd salyut-bbs     -
d /run/salyut-bbs/users 2770 salyut-bbsd salyut-bbs     -
d /run/salyut-bbs/web   2770 salyut-bbsd salyut-bbs-web -
d /var/lib/salyut-bbs   0750 salyut-bbsd salyut-bbs     -
